In [6]:
import numpy as np
import pandas as pd
import sys
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:

# 100% correctness and performance
def solution(A):
    N = len(A)
    return sum(range(1, N+2)) - sum(A)

In [8]:
A = [2, 3, 1, 5]
A = []
A = [2]
A = [0, 3]
solution(A)
A = list(range(1, 100000))
A.remove(99999)
A[:3]
A[-3:]
# %timeit solution(A)
# %timeit solution1(A)

3

[1, 2, 3]

[99996, 99997, 99998]

In [84]:
a = np.array([i for i in range(20)])
a
A = a.reshape(4,5)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
A[::-1,::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [114]:
*a, b= A
a
b

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

array([15, 16, 17, 18, 19])

In [100]:
# A[1:,:3]
# A[0,:]
# A[-1, :]
# A[1:-1, :]
# list(zip(*A))
list(zip(*A[::-1,::-1]))

[(19, 14, 9, 4),
 (18, 13, 8, 3),
 (17, 12, 7, 2),
 (16, 11, 6, 1),
 (15, 10, 5, 0)]

In [73]:
def solution(A):
    n, m = A.shape
    up_spiral = []
    low_spiral = []
    for i in range(n):
        print(i, j)
        if A.shape[0] > 0:   
            up_spiral += A[0,:]
            A = A[1:, :]
        if A.shape[0] > 0:
            low_spiral += A[-1,:]
            A = A[:-1, :]

        if A.shape[0] > 0:
            A[] = 
            
    
    

In [74]:
solution(A)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4


In [27]:

def solution(N):
    L = 0
    R = 1
    ops = ['L', 'R']
    success = False
#     comL = 2*L - R
#     comR = 2*R - L
     
#     for i in range(1, N+1):
    while not success:
        if L 
        for op in ops:
            if op == 'L':
                L = 2*L -R
            elif op == 'R':
                R = 2*R -L
            if L == N or R == N:
                print('ok')
                success = True
            print(op, L, R)
    return 'impossible'
            
    

In [53]:

def solution(N):
    L = 0
    R = 1
    if N == 0 or N == 1:
        print('no operaton need')
        return 'impossible'
    
    while N - R > 0:
        R = 2*R -L
        print(L, R)
    while N - L < 0:
        L = 2*L -R
        print(L, R)
    if N ==R or N ==L:
        
        
        print(L, R)
    return 'impossible'
            
    

In [54]:
solution(-11)

-1 1
-3 1
-7 1
-15 1


'impossible'