In [10]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [1]:
from IPython.display import YouTubeVideo
# YouTubeVideo('fwNLf4t7MR8', width=800, height=450)
# https://www.youtube.com/watch?v=7PiK4wtfvbA&list=PLBAGcD3siRDguyYYzhVwZ3tLvOyyG5k6K
YouTubeVideo('7PiK4wtfvbA', width=800, height=450)
# 7PiK4wtfvbA&list=PLBAGcD3siRDguyYYzhVwZ3tLvOyyG5k6K

In [34]:
# back propagation
# 10 input nodes, 2 output nodes
# https://medium.com/@karpathy/yes-you-should-understand-backprop-e2f06eab496b

In [45]:
W = np.random.rand(2,10)
W
# when W intialized with very large numbers.
W = W*(-1)
W
W.shape
W.T.shape
x = np.random.rand(10)
x


array([[0.13996526, 0.9235979 , 0.68102035, 0.6719294 , 0.80753745,
        0.92666201, 0.35465141, 0.00562771, 0.48754263, 0.64805251],
       [0.85242218, 0.56608297, 0.62136131, 0.34828225, 0.31495049,
        0.98214448, 0.67160636, 0.61136238, 0.72741996, 0.51613446]])

array([[-0.13996526, -0.9235979 , -0.68102035, -0.6719294 , -0.80753745,
        -0.92666201, -0.35465141, -0.00562771, -0.48754263, -0.64805251],
       [-0.85242218, -0.56608297, -0.62136131, -0.34828225, -0.31495049,
        -0.98214448, -0.67160636, -0.61136238, -0.72741996, -0.51613446]])

(2, 10)

(10, 2)

array([0.10115639, 0.57838524, 0.70577263, 0.97019748, 0.53457684,
       0.2325809 , 0.47958349, 0.66956244, 0.89733136, 0.93944134])

In [36]:
z = 1/(1 + np.exp(-np.dot(W, x))) # forward pass
z

array([1., 1.])

In [37]:
z = 1/(1 + np.exp(-np.dot(W, x))) # forward pass
dx = np.dot(W.T, z*(1-z)) # backward pass: local gradient for x
dW = np.outer(z*(1-z), x) # backward pass: local gradient for W

In [38]:
z
dx
dW

array([1., 1.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
z = np.maximum(0, np.dot(W, x)) # forward pass
dW = np.outer(z > 0, x) # backward pass: local gradient for W

In [47]:
z
dW

array([0., 0.])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])