In [18]:
import torch
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [10]:
a = torch.tensor([1,2,3])
b = torch.tensor([10,20,30])

In [9]:
a * 3

tensor([3, 6, 9])

In [32]:
torch.tensor((a * a).sum()).sqrt()

/projects/da_workspace/software/miniconda/envs/fastai/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


RuntimeError: "sqrt" not implemented for 'torch.LongTensor'

In [29]:
(a * a).sum().sqrt()

RuntimeError: "sqrt" not implemented for 'torch.LongTensor'

In [12]:
(a * b).sum()

tensor(140)

In [14]:
c = 0
for i in range(3):
    print(i)
    c += a[i] * b[i]
print(c)

0
1
2
tensor(140)


In [16]:
a.shape
a @ b

tensor(140)

In [25]:
# trailing ,: can be deleted; leading :,:, can be replaced with ...,
a[None,:]
a[None]
a[:, None]
a[...,None]
a[None,:] @ b[:, None]
b[:, None] @ a[None,:]

tensor([[1, 2, 3]])

tensor([[1, 2, 3]])

tensor([[1],
        [2],
        [3]])

tensor([[1],
        [2],
        [3]])

tensor([[140]])

tensor([[10, 20, 30],
        [20, 40, 60],
        [30, 60, 90]])

In [26]:
# matmul has 3 loops, can be replaced by element-wise multiplication, broadcasting, and einstein summation
# so without loops

In [28]:
17237/60/60

4.788055555555556