In [3]:
import numpy as np
from tqdm import tqdm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%load_ext blackcellmagic


In [8]:
for i in tqdm(range(int(1e5))):
    pass

100%|██████████| 100000/100000 [00:00<00:00, 1263192.39it/s]


# p value

In statistic hypothesis testing, p value is the probability of oberserving the results or more extreme results if the null hypothesis is true.

# central limit theorem

# q value

# FDR
control the false discovery rate for multiple hyothesis testings

https://www.jstor.org/stable/2346101?seq=1#metadata_info_tab_contents

In [35]:
# order p values in ascending order
p = np.array([0.001, 0.0004, 0.0019, 0.0095, 0.0201, 0.0278, 0.0298, 0.0344, 0.0459, 0.3240, 0.4262, 0.5719, 0.6528, 0.7590, 1.000])
p

array([1.000e-03, 4.000e-04, 1.900e-03, 9.500e-03, 2.010e-02, 2.780e-02,
       2.980e-02, 3.440e-02, 4.590e-02, 3.240e-01, 4.262e-01, 5.719e-01,
       6.528e-01, 7.590e-01, 1.000e+00])

## procedure 1: Bonferroni approach
use 0.05/15 as cutoff. I think this is very stringent. it means if i do 15 tests, to reject the null hypotheses, the p value must < 0.05 (significant level)/15 (the number of tests.)


In [34]:
bon = 0.05/15; bon
p < bon # reject the first 3 hypothesis

0.0033333333333333335

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

## Hocheberge procedure
order p value from smallest to largest, then compare p value to its Hochberge value alpha/(k-j+1), k is number of tests, j is the order of p vlaue.

In [51]:
alpha = 0.05
hs = np.array([alpha / (15 - j + 1) for j in range(1, 16)])
hs

p < hs

array([0.00333333, 0.00357143, 0.00384615, 0.00416667, 0.00454545,
       0.005     , 0.00555556, 0.00625   , 0.00714286, 0.00833333,
       0.01      , 0.0125    , 0.01666667, 0.025     , 0.05      ])

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

## Benjamini–Hochberg FDR controlling procedure

In [53]:
# pick a q threshold false discovery rate is 5%
q = 0.05
# compare p with q*i/15 sequentially starting from the largest p
bhs = np.array([q * j / 15 for j in range(1, 16)])
bhs


p < bhs  # reject first 4 hypothesis

array([0.00333333, 0.00666667, 0.01      , 0.01333333, 0.01666667,
       0.02      , 0.02333333, 0.02666667, 0.03      , 0.03333333,
       0.03666667, 0.04      , 0.04333333, 0.04666667, 0.05      ])

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [9]:
#export
print('this is a test cell!')

this is a test cell!


# EXPORT

In [12]:
!python notebook2script.py statisticas_20191004.ipynb

Converted statisticas_20191004.ipynb to exp/nb_statisticas_20191004.py
